#spring.application.name=SpringAI
spring:
  application:
    name: IMAGE-SERVICE
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      image:
        options:
          size: 1024x1024 #to generate an image without options it requires at least specifying the size
server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka